id: I42B3841A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:40:20+00:00'
last_modified: '2022-06-08T03:24:58.814707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5198
  title: དབྱངས་ཀྱི་སྐུད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5656':
      image_group_id: I3CN5200
      title: ''
      total_pages: 164
      order: 1
      base_file: 5656.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
