id: P005484
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5198
  title: དབྱངས་ཀྱི་སྐུད་པ།
  author: ''
  volumes:
    3a1fb754c3d94af9b3b28336eb7ff75e:
      image_group_id: I3CN5200
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
